import { expect, test } from './fixtures'

test('carrusel: límites, categorías, detalle, siguiente y retorno exacto', async ({ page }) => {
  await page.goto('/proyectos')
  const title = page.locator('main h1')
  await expect(title).toHaveAccessibleName('Nocturne Studio')
  await page.getByRole('button', { name: 'Proyecto anterior', exact: true }).click()
  await expect(title).toHaveAccessibleName('Atlas Learning')
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect(title).toHaveAccessibleName('Nocturne Studio')
  await page.getByRole('button', { name: 'Personal', exact: true }).click()
  await expect(title).toHaveAccessibleName('Synthwave Lab')
  await expect(page.locator('main')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect(title).toHaveAccessibleName('Kanji Quest')
  await page.getByRole('link', { name: 'Abrir Kanji Quest', exact: true }).click()
  await expect(page).toHaveURL(/\/proyectos\/kanji\?category=personal&slug=kanji$/)
  await expect(page.getByRole('button', { name: 'Ver en vivo', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Código', exact: true })).toBeDisabled()
  await page.getByRole('link', { name: /Siguiente proyecto.*Phantom UI Kit/i }).click()
  await expect(title).toHaveAccessibleName('Phantom UI Kit')
  await page.getByRole('link', { name: /Volver a proyectos/ }).click()
  await expect(title).toHaveAccessibleName('Kanji Quest')
  await expect(page.locator('main')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(title).toHaveAccessibleName('Kanji Quest')
  await page.getByRole('button', { name: 'Profesional', exact: true }).click()
  await expect(title).toHaveAccessibleName('Nocturne Studio')
})

test('teclado, selección visible y Escape contextual en detalle', async ({ page }) => {
  await page.goto('/proyectos?category=personal&slug=p5ui&source=bookmark')
  await expect(page.locator('main h1')).toHaveAccessibleName('Phantom UI Kit')
  await page.locator('main').focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('main h1')).toHaveAccessibleName('Synthwave Lab')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/proyectos\/synth\?/)
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page).toHaveURL(/\/proyectos\/synth\?/)
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/\/proyectos\?/)
  await expect(page.locator('main h1')).toHaveAccessibleName('Synthwave Lab')
  expect(new URL(page.url()).searchParams.get('source')).toBe('bookmark')
})

test('la selección por tarjeta y el cambio de idioma conservan el proyecto', async ({ page }) => {
  await page.goto('/proyectos')
  await page.getByRole('link', { name: 'Seleccionar Velvet Commerce', exact: true }).click()
  await expect(page.locator('main h1')).toHaveAccessibleName('Velvet Commerce')
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'EN', exact: true }).click()
  await expect(page).toHaveURL(/\/en\/projects\?category=pro&slug=velvet$/)
  await expect(page.locator('main h1')).toHaveAccessibleName('Velvet Commerce')
  await page.getByRole('link', { name: 'Open Velvet Commerce', exact: true }).click()
  await expect(page.locator('main')).toContainText('A custom online store')
})

test('gesto táctil horizontal cambia de tarjeta sin abrir detalle', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/proyectos')
  const card = page.locator('[data-project-card][aria-current="true"]')
  const bounds = await card.boundingBox()
  expect(bounds).not.toBeNull()
  const session = await context.newCDPSession(page)
  const startX = bounds!.x + bounds!.width * .75
  const startY = bounds!.y + bounds!.height * .5
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: startX, y: startY }] })
  for (let step = 1; step <= 6; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: startX - step * 22, y: startY }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('main h1')).toHaveAccessibleName('Velvet Commerce')
  await expect(page).toHaveURL(/\/proyectos\?/)
  await session.detach()
})
