import { expect, test } from './fixtures'

test('carrusel: límites, categorías, detalle, siguiente y retorno exacto', async ({ page }) => {
  await page.goto('/proyectos')
  const title = page.locator('main h1')
  await expect(title).toHaveAccessibleName('Sites Builder')
  await page.getByRole('button', { name: 'Proyecto anterior', exact: true }).click()
  await expect(title).toHaveAccessibleName('Ascensores Cemar')
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect(title).toHaveAccessibleName('Sites Builder')
  await page.getByRole('button', { name: 'Personal', exact: true }).click()
  await expect(title).toHaveAccessibleName('OG Stickers')
  await expect(page.locator('main')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect(title).toHaveAccessibleName('Snkrz Garden')
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect(title).toHaveAccessibleName('Moof Fisioterapia')
  await page.getByRole('link', { name: 'Abrir Moof Fisioterapia', exact: true }).click()
  await expect(page).toHaveURL(/\/proyectos\/moof\?category=personal&slug=moof$/)
  await expect(page.getByRole('link', { name: 'Ver en vivo', exact: true })).toHaveAttribute('href', 'https://moof.es')
  await expect(page.getByRole('button', { name: 'Código', exact: true })).toBeDisabled()
  await page.getByRole('link', { name: /Siguiente proyecto.*Argenis y Carolina/i }).click()
  await expect(title).toHaveAccessibleName('Argenis y Carolina')
  await page.getByRole('link', { name: /Volver a proyectos/ }).click()
  await expect(title).toHaveAccessibleName('Moof Fisioterapia')
  await expect(page.locator('main')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(title).toHaveAccessibleName('Moof Fisioterapia')
  await page.getByRole('button', { name: 'Profesional', exact: true }).click()
  await expect(title).toHaveAccessibleName('Sites Builder')
})

test('teclado, selección visible y Escape contextual en detalle', async ({ page }) => {
  await page.goto('/proyectos?category=personal&slug=ayc&source=bookmark')
  await expect(page.locator('main h1')).toHaveAccessibleName('Argenis y Carolina')
  await page.locator('main').focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('main h1')).toHaveAccessibleName('OG Stickers')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/proyectos\/og-stickers\?/)
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page).toHaveURL(/\/proyectos\/og-stickers\?/)
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/\/proyectos\?/)
  await expect(page.locator('main h1')).toHaveAccessibleName('OG Stickers')
  expect(new URL(page.url()).searchParams.get('source')).toBe('bookmark')
})

test('la selección por tarjeta y el cambio de idioma conservan el proyecto', async ({ page }) => {
  await page.goto('/proyectos')
  await expect(page.locator('.project-static-list')).toHaveCount(0)
  const nextCard = await page.getByRole('link', { name: 'Seleccionar SeatGeek Sites', exact: true }).boundingBox()
  expect(nextCard).not.toBeNull()
  await page.mouse.click(nextCard!.x + nextCard!.width * .9, nextCard!.y + nextCard!.height * .5)
  await expect(page.locator('main h1')).toHaveAccessibleName('SeatGeek Sites')
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'EN', exact: true }).click()
  await expect(page).toHaveURL(/\/en\/projects\?category=pro&slug=seatgeek-sites$/)
  await expect(page.locator('main h1')).toHaveAccessibleName('SeatGeek Sites')
  await page.getByRole('link', { name: 'Open SeatGeek Sites', exact: true }).click()
  await expect(page.locator('main')).toContainText('Season-ticket relocation and sales portals')
})

test('gesto táctil horizontal cambia de tarjeta sin abrir detalle', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/proyectos')
  await expect(page.locator('.project-static-list')).toHaveCount(0)
  const card = page.locator('[data-project-card][aria-current="true"]')
  const bounds = await card.boundingBox()
  expect(bounds).not.toBeNull()
  const session = await context.newCDPSession(page)
  const startX = bounds!.x + bounds!.width * .75
  const startY = bounds!.y + bounds!.height * .5
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: startX, y: startY }] })
  for (let step = 1; step <= 6; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: startX - step * 22, y: startY }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('main h1')).toHaveAccessibleName('SeatGeek Sites')
  await expect(page).toHaveURL(/\/proyectos\?/)
  await session.detach()
})

test('galería: el visor amplía, navega con flechas y Escape devuelve el foco sin salir del detalle', async ({ page }) => {
  await page.goto('/proyectos/psp-chelsea-fc')
  const trigger = page.getByRole('link', { name: /^Ampliar: Mapa 3D de Stamford Bridge/ })
  await trigger.click()
  const viewer = page.getByRole('dialog', { name: 'Galería de PSP Chelsea FC', exact: true })
  await expect(viewer).toBeVisible()
  await expect(viewer).toContainText('Imagen 2 de 11')
  await page.keyboard.press('ArrowRight')
  await expect(viewer.locator('figure img')).toHaveAttribute('src', '/projects/chelsea/event-schedule.webp')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await expect(viewer.locator('figure img')).toHaveAttribute('src', '/projects/chelsea/mobile-menu.webp')
  await page.keyboard.press('Escape')
  await expect(viewer).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await expect(page).toHaveURL(/\/proyectos\/psp-chelsea-fc$/)
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
})

test('sites builder enlaza sus sites en producción en otra pestaña con su favicon', async ({ page }) => {
  await page.goto('/proyectos/sites-builder')
  const sites = page.getByRole('region', { name: 'Sites en producción', exact: true })
  await expect(sites).toContainText('Una muestra de más de 600 sites publicados.')
  const links = sites.getByRole('link')
  await expect(links).toHaveCount(12)
  const angels = sites.getByRole('link', { name: 'LA Angels (se abre en una pestaña nueva)', exact: true })
  await expect(angels).toHaveAttribute('href', 'https://preview.3ddigitalvenue.com/la-angels')
  await expect(angels).toHaveAttribute('target', '_blank')
  await expect(angels).toHaveAttribute('rel', 'noopener noreferrer')
  const icons = sites.locator('img')
  await icons.last().scrollIntoViewIfNeeded()
  await expect.poll(() => icons.evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
})

test('la tarjeta principal abre el velo de puntillismo y las vecinas lo conservan en blanco y negro', async ({ page }) => {
  await page.goto('/proyectos')
  const veil = (card: number) => page.locator('[data-project-card]').nth(card).locator('.card-dots--left')
  await expect.poll(() => veil(0).evaluate(element => getComputedStyle(element).transform)).not.toBe('none')
  await expect.poll(() => veil(1).evaluate(element => getComputedStyle(element).transform)).toBe('none')
  await expect(page.locator('[data-project-card]').first().locator('.project-cover')).toHaveCSS('filter', /grayscale\(1\)/)
  await page.getByRole('button', { name: 'Proyecto siguiente', exact: true }).click()
  await expect.poll(() => veil(1).evaluate(element => getComputedStyle(element).transform)).not.toBe('none')
  await expect.poll(() => veil(0).evaluate(element => getComputedStyle(element).transform)).toBe('none')
})
