/** Exportaciones del sistema; los contratos de props y eventos se conservan al importar desde este módulo. */
export { default as P5Button } from './P5Button.vue'
export { default as P5Tag } from './P5Tag.vue'
export { default as P5Badge } from './P5Badge.vue'
export { default as P5Stamp } from './P5Stamp.vue'
export { default as P5Heading } from './P5Heading.vue'
export { default as P5Card } from './P5Card.vue'
export { default as P5FactCard } from './P5FactCard.vue'
export { default as P5Input } from './P5Input.vue'
export { default as P5Textarea } from './P5Textarea.vue'
export { default as P5NavItem } from './P5NavItem.vue'
export { default as P5Kbd } from './P5Kbd.vue'
export { default as P5Switch } from './P5Switch.vue'
export { default as P5Wipe } from './P5Wipe.vue'
export { default as P5Placeholder } from './P5Placeholder.vue'
